function [Ox,Oy,Oz,sx,sy,sz] = extractMetaFromNifti(meta)
    origin = meta.Transform.T(4,[1:3]);
    spacing = meta.PixelDimensions;
    Ox = origin(1);
    Oy = origin(2);
    Oz = origin(3);
    sx = spacing(1);
    sy = spacing(2);
    sz = spacing(3);